<?php
$aMeses = array(
               "Enero"=>array(
                            "ndias"=>31,
                            "festivos"=>array(
                                            array("dia"=>1,
                                                  "tipo"=>"Nacional"),
                                            array("dia"=>6,
                                                  "tipo"=>"Nacional")
                                       )
                         ),
                "Febrero"=>array(
                            "ndias"=>28,
                            "festivos"=>array(
                                            array("dia"=>28,
                                                  "tipo"=>"Comunidad")
                                    )
                        ),
                "Marzo"=>array(
                            "ndias"=>31,
                            "festivos"=>array()
                        ),
                "Abril"=>array(
                            "ndias"=>30,
                            "festivos"=>array()
                        ),
                "Mayo"=>array(
                            "ndias"=>31,
                            "festivos"=>array(
                                            array("dia"=>1,
                                                  "tipo"=>"Nacional")
                                         )
                        ),
                "Junio"=>array(
                            "ndias"=>30,
                            "festivos"=>array()
                        ),
                "Julio"=>array(
                            "ndias"=>31,
                            "festivos"=>array()
                        ),
                "Agosto"=>array(
                            "ndias"=>31,
                            "festivos"=>array(
                                            array("dia"=>15,
                                                  "tipo"=>"Nacional")
                                        )
                        ),
                "Septiembre"=>array(
                            "ndias"=>30,
                            "festivos"=>array(
                                            array("dia"=>8,
                                                  "tipo"=>"Local")
                                    )
                            ),
                "Octubre"=>array(
                            "ndias"=>31,
                            "festivos"=>array(
                                            array("dia"=>12,
                                                  "tipo"=>"Nacional"),
                                            array("dia"=>24,
                                                  "tipo"=>"Local")
                                        )
                            ),
                "Noviembre"=>array(
                            "ndias"=>30,
                            "festivos"=>array(
                                            array("dia"=>1,
                                                  "tipo"=>"Nacional")
                                    )
                            ),
                "Diciembre"=>array(
                            "ndias"=>31,
                            "festivos"=>array(
                                            array("dia"=>1,
                                                  "tipo"=>"Nacional"),
                                                  array("dia"=>6,
                                                  "tipo"=>"Nacional"),
                                                  array("dia"=>8,
                                                  "tipo"=>"Nacional"),
                                                  array("dia"=>25,
                                                  "tipo"=>"Nacional")
                                    )
                               
                        )
            );